### ISSUE TITLE
how to comp

### ISSUE THREAD

**Issue by EGAMatsu** [repnz/ReversingMinesweeper#3]
how tf do i compile

**Comment by JPeisach** [comment]
I'll probably setup a build system and PR it. Use a compiler like gcc or mingw although you may need a legacy one

**Comment by repnz** [comment]
Hey:) you can use visual studio to build it, but it's not finished yet and not tested so it won't work

**Comment by JPeisach** [comment]
Yeah but technically for packaging a Makefile would be best :)

Also lots of people don't prefer VSCode, no insult just saying... like me :P

Also I believe with the header files of windows you'll need the shared libraries (.so/.la) I think, so we may need a bit more.
